### ISSUE TITLE
Project has a server

### ISSUE THREAD

**Issue by eldamir** [eldamir/RuntimeErrorGame#1]
The project needs a server class to listen for incoming API events.

Implement with a simple vertx verticle

- [x] Implement a game loop on the server
- [x] Let players connect to the server
- [x] Send the updated game state to the players

**Comment by Kimmax** [comment]
Not sure if we should make it REST Api (Servicestack would be great for that) or a simple TCP Server with a minimalistic client-server protocol.
Many monitoring solutions have such a protocol for simple plugin output exchange, which grants wide possibilities for script languages.
Something like
`Entity|Action|Parameter|Parameter2|...`

**Comment by eldamir** [comment]
Depending on what kind of instructions we want the players to give, REST may have too big an overhead. If we want to provide something like rotate left 30 degrees, increase throttle to 60, fire main gun, etc. I fear the overhead of the request-response cycle of HTTP will be a problem.

So for direct control, I think a custom TCP protocol may be needed (unless something exists, that I am not aware of).

For querying player assets, a REST framework over HTTP would be fine.

**Comment by Kimmax** [comment]
That sounds fine. Didn't thought of combining both

**Comment by eldamir** [comment]
Reading about [Game loop](http://gameprogrammingpatterns.com/game-loop.html), I believe I know enough to design a first iteration.

The game will just be a spaceship being moved around in memory. Then a visual representation can be implemented. Then user input can be implemented.

The structure of the code will be something like the following

- `ClientConnectionHandler` receives connections from players and receives messages from them. Messages are converted to user input events that can be fired
- `GameStateDriver` contains the main loop and controls mutation of state in three steps
    - Respond to user input event and mutate state
    - Mutate state based on time
    - Fire state update event for other parts of the system to respond to
- `GameStateBroadcaster` responds to game state update events and sends representations of the state changes to relevant entities, e.g. player's GUI and player's client code

Seems like a decent fit. Will try to jumble it together
